import {
    DEFAULT_FOUNDER_SETTINGS,
    FOUNDER_OS_CONTRACT_VERSION,
    type FounderDashboardSnapshot,
} from '@/lib/founder-os/contracts';

export interface BeatMatchSummary {
    id: string;
    title: string;
    genre: string;
    reason: string;
    href: string | null;
    offerLabel: string;
    resolution?: 'demo' | 'catalog' | 'missing';
}

export interface IntelligenceSignal {
    id: string;
    label: string;
    value: string;
    context: string;
    status: 'available' | 'partial' | 'blocked';
}

export const DEMO_BEAT_DIRECTORY: Record<string, BeatMatchSummary> = {
    'hardcore-phonk': {
        id: 'hardcore-phonk',
        title: 'HARDCORE PHONK',
        genre: 'Cyberpunk Phonk',
        reason: 'Dark, high-energy palette fits aggressive delivery and short-form edits.',
        href: '/studio/beats/hardcore-phonk',
        offerLabel: 'Basic MP3 · $15 · recording use',
    },
    '808-danger-line': {
        id: '808-danger-line',
        title: '808 Danger Line',
        genre: 'Cyberpunk Trap',
        reason: 'Hard 808 movement supports bilingual rap hooks and gaming montage cuts.',
        href: '/studio/beats/808-danger-line',
        offerLabel: 'Basic MP3 · $15 · recording use',
    },
    'cyber-runner': {
        id: 'cyber-runner',
        title: 'CYBER RUNNER',
        genre: 'Cyberpunk Trap',
        reason: 'Fast, cinematic energy maps to action trailers and competitive gaming.',
        href: '/studio/beats/cyber-runner',
        offerLabel: 'Custom sync inquiry for interactive use',
    },
    'syn808-cyberpunk-synthwave-trap-beat': {
        id: 'syn808-cyberpunk-synthwave-trap-beat',
        title: 'SYN808',
        genre: 'Synthwave Trap',
        reason: 'Retro-futuristic texture fits sci-fi worlds and narrative creator content.',
        href: '/studio/beats/syn808-cyberpunk-synthwave-trap-beat',
        offerLabel: 'Custom sync inquiry for creator/game use',
    },
    desync: {
        id: 'desync',
        title: 'DESYNC',
        genre: 'Synthwave Trap',
        reason: 'Atmospheric tension works for video essays, reveals, and dystopian scenes.',
        href: '/studio/beats/desync',
        offerLabel: 'Custom sync inquiry for creator use',
    },
};

export const DEMO_INTELLIGENCE_SIGNALS: IntelligenceSignal[] = [
    {
        id: 'catalog',
        label: 'Beat catalog',
        value: '325 tracks',
        context: 'Repository source is available; offer eligibility is still validated server-side.',
        status: 'available',
    },
    {
        id: 'meta',
        label: 'Meta performance',
        value: 'Not connected',
        context: 'No reach, saves, audience, comment, or inbound-message data is being inferred.',
        status: 'blocked',
    },
    {
        id: 'tiktok',
        label: 'TikTok performance',
        value: 'Not connected',
        context: 'FYP performance cannot be assessed until owned-account data is authorized.',
        status: 'blocked',
    },
    {
        id: 'research',
        label: 'Lead research',
        value: '3 lanes staged',
        context: 'Rapper first, followed by game developers and content creators.',
        status: 'partial',
    },
];

export const DEMO_FOUNDER_OS_SNAPSHOT: FounderDashboardSnapshot = {
    contractVersion: FOUNDER_OS_CONTRACT_VERSION,
    generatedAt: '2026-07-29T08:45:00.000Z',
    mode: 'demo',
    agents: [
        {
            id: 'chief-of-staff',
            name: 'Chief of Staff',
            role: 'Prioritizes work, delegates bounded tasks, and prepares the founder brief.',
            status: 'working',
            currentTask: 'Reviewing the highest-leverage actions for today',
            lastRunAt: '2026-07-29T08:42:00.000Z',
            evidenceCount: 14,
        },
        {
            id: 'lead-scout',
            name: 'A&R Lead Scout',
            role: 'Finds and qualifies potential beat buyers with source-backed evidence.',
            status: 'waiting-for-approval',
            currentTask: 'Three rapper prospects are ready for founder review',
            lastRunAt: '2026-07-29T08:31:00.000Z',
            evidenceCount: 21,
        },
        {
            id: 'growth-analyst',
            name: 'Growth Intelligence',
            role: 'Turns owned performance data into testable content hypotheses.',
            status: 'blocked',
            currentTask: 'Waiting for Meta and TikTok account connections',
            lastRunAt: null,
            evidenceCount: 0,
        },
        {
            id: 'content-strategist',
            name: 'Content Strategist',
            role: 'Builds hooks, formats, creative briefs, and experiment plans.',
            status: 'idle',
            currentTask: 'Ready for a source-backed campaign brief',
            lastRunAt: '2026-07-29T07:55:00.000Z',
            evidenceCount: 8,
        },
        {
            id: 'outreach-operator',
            name: 'Outreach Operator',
            role: 'Drafts personalized sequences but can never send without approval.',
            status: 'waiting-for-approval',
            currentTask: 'Two email drafts require review; social cold DMs are locked',
            lastRunAt: '2026-07-29T08:18:00.000Z',
            evidenceCount: 11,
        },
    ],
    prospects: [
        {
            id: 'prospect-kairo',
            displayName: 'Kairo Vale',
            handle: '@kairovale.demo',
            segment: 'rapper',
            market: 'en-US',
            platform: 'youtube',
            profileUrl: null,
            businessEmail: 'management@kairovale.example',
            contactPermission: 'public-business-email',
            score: 86,
            scoreBreakdown: {
                audienceFit: 18,
                styleFit: 27,
                purchaseIntent: 18,
                contactability: 14,
                freshness: 9,
            },
            matchedBeatIds: ['808-danger-line', 'hardcore-phonk'],
            signals: [
                'Released a dark trap performance video inside the last 30 days.',
                'Public booking email is listed on the official channel profile.',
                'Recent sound direction overlaps the Cyberpunk Trap catalog lane.',
            ],
            gaps: ['No verified release budget.', 'No owned interaction history yet.'],
            evidence: [
                {
                    id: 'ev-kairo-channel',
                    label: 'Official channel profile',
                    url: null,
                    sourceType: 'manual-research',
                    observedAt: '2026-07-28T13:10:00.000Z',
                    freshness: 'fresh',
                    note: 'Demo evidence only; production records require the real source URL.',
                },
                {
                    id: 'ev-kairo-release',
                    label: 'Recent performance upload',
                    url: null,
                    sourceType: 'manual-research',
                    observedAt: '2026-07-26T18:20:00.000Z',
                    freshness: 'fresh',
                },
            ],
            lastObservedAt: '2026-07-28T13:10:00.000Z',
        },
        {
            id: 'prospect-mika',
            displayName: 'Mika Rei',
            handle: '@mikarei.demo',
            segment: 'rapper',
            market: 'ja-JP',
            platform: 'instagram',
            profileUrl: null,
            businessEmail: null,
            contactPermission: 'manual-only',
            score: 78,
            scoreBreakdown: {
                audienceFit: 16,
                styleFit: 25,
                purchaseIntent: 17,
                contactability: 10,
                freshness: 10,
            },
            matchedBeatIds: ['hardcore-phonk', 'syn808-cyberpunk-synthwave-trap-beat'],
            signals: [
                'Published a bilingual cyber-styled freestyle within 14 days.',
                'Visual identity and delivery align with the Phonk and Synthwave lanes.',
            ],
            gaps: [
                'No public business email found.',
                'Language confidence needs founder review before copy approval.',
            ],
            evidence: [
                {
                    id: 'ev-mika-post',
                    label: 'Recent public freestyle',
                    url: null,
                    sourceType: 'manual-research',
                    observedAt: '2026-07-27T04:30:00.000Z',
                    freshness: 'fresh',
                    note: 'Manual handoff only. The system will not initiate a cold Instagram DM.',
                },
            ],
            lastObservedAt: '2026-07-27T04:30:00.000Z',
        },
        {
            id: 'prospect-neon-ronin',
            displayName: 'Neon Ronin Studio',
            handle: null,
            segment: 'game-developer',
            market: 'ja-JP',
            platform: 'website',
            profileUrl: null,
            businessEmail: 'audio@neonronin.example',
            contactPermission: 'public-business-email',
            score: 74,
            scoreBreakdown: {
                audienceFit: 14,
                styleFit: 24,
                purchaseIntent: 15,
                contactability: 13,
                freshness: 8,
            },
            matchedBeatIds: ['cyber-runner', 'syn808-cyberpunk-synthwave-trap-beat'],
            signals: [
                'Active cyber-racing prototype with a recent development update.',
                'Public studio contact explicitly accepts audio partnership inquiries.',
            ],
            gaps: [
                'In-game, trailer, soundtrack, and territory rights are not yet scoped.',
                'Requires a custom sync inquiry; standard recording license is ineligible.',
            ],
            evidence: [
                {
                    id: 'ev-neon-devlog',
                    label: 'Studio development update',
                    url: null,
                    sourceType: 'manual-research',
                    observedAt: '2026-07-20T09:00:00.000Z',
                    freshness: 'fresh',
                },
            ],
            lastObservedAt: '2026-07-20T09:00:00.000Z',
        },
        {
            id: 'prospect-cutscene',
            displayName: 'Cutscene Theory',
            handle: '@cutscenetheory.demo',
            segment: 'content-creator',
            market: 'de-DE',
            platform: 'youtube',
            profileUrl: null,
            businessEmail: 'partners@cutscenetheory.example',
            contactPermission: 'public-business-email',
            score: 71,
            scoreBreakdown: {
                audienceFit: 15,
                styleFit: 22,
                purchaseIntent: 13,
                contactability: 13,
                freshness: 8,
            },
            matchedBeatIds: ['desync', 'cyber-runner'],
            signals: [
                'Publishes gaming video essays with recurring background-music needs.',
                'Recent dystopian game analysis matches the catalog aesthetic.',
            ],
            gaps: [
                'Commercial video scope and client-work usage are unverified.',
                'Requires custom creator sync terms before any rights claim.',
            ],
            evidence: [
                {
                    id: 'ev-cutscene-upload',
                    label: 'Recent channel upload',
                    url: null,
                    sourceType: 'manual-research',
                    observedAt: '2026-07-23T16:40:00.000Z',
                    freshness: 'fresh',
                },
            ],
            lastObservedAt: '2026-07-23T16:40:00.000Z',
        },
    ],
    approvals: [
        {
            id: 'approval-kairo-step-1',
            actionType: 'outreach-send',
            channel: 'email',
            status: 'READY_FOR_APPROVAL',
            targetLabel: 'Kairo Vale · Sequence 1/3',
            payloadSummary: 'Personalized introduction with two matched beat links and a reply CTA.',
            contentHash: 'sha256:demo-kairo-revision-3',
            createdAt: '2026-07-29T08:20:00.000Z',
            updatedAt: '2026-07-29T08:34:00.000Z',
            approvedAt: null,
            executedAt: null,
            providerReference: null,
            failureReason: null,
        },
        {
            id: 'approval-neon-sync',
            actionType: 'outreach-send',
            channel: 'email',
            status: 'READY_FOR_APPROVAL',
            targetLabel: 'Neon Ronin Studio · Custom sync inquiry',
            payloadSummary: 'Scope-first introduction; no recording-license rights are promised.',
            contentHash: 'sha256:demo-neon-revision-1',
            createdAt: '2026-07-29T08:12:00.000Z',
            updatedAt: '2026-07-29T08:12:00.000Z',
            approvedAt: null,
            executedAt: null,
            providerReference: null,
            failureReason: null,
        },
        {
            id: 'approval-mika-manual',
            actionType: 'outreach-send',
            channel: 'instagram',
            status: 'DRAFT',
            targetLabel: 'Mika Rei · Manual handoff',
            payloadSummary: 'Copy reference only. Cold social API delivery remains prohibited.',
            contentHash: 'sha256:demo-mika-revision-1',
            createdAt: '2026-07-29T07:58:00.000Z',
            updatedAt: '2026-07-29T07:58:00.000Z',
            approvedAt: null,
            executedAt: null,
            providerReference: null,
            failureReason: null,
        },
        {
            id: 'approval-content-plan',
            actionType: 'social-publish',
            channel: 'tiktok',
            status: 'DRAFT',
            targetLabel: 'TikTok content experiment',
            payloadSummary: 'Hypothesis draft only; TikTok is not connected and no publish can run.',
            contentHash: 'sha256:demo-content-revision-1',
            createdAt: '2026-07-29T07:42:00.000Z',
            updatedAt: '2026-07-29T07:42:00.000Z',
            approvedAt: null,
            executedAt: null,
            providerReference: null,
            failureReason: null,
        },
    ],
    settings: {
        ...DEFAULT_FOUNDER_SETTINGS,
        markets: [...DEFAULT_FOUNDER_SETTINGS.markets],
        segmentPriority: [...DEFAULT_FOUNDER_SETTINGS.segmentPriority],
        trendSources: { ...DEFAULT_FOUNDER_SETTINGS.trendSources },
        integrations: { ...DEFAULT_FOUNDER_SETTINGS.integrations },
    },
    evidence: [
        {
            id: 'ev-catalog',
            label: 'VGP beat catalog',
            url: '/studio/beats',
            sourceType: 'repository',
            observedAt: '2026-07-29T08:00:00.000Z',
            freshness: 'fresh',
            note: 'Catalog availability is separate from license-offer eligibility.',
        },
        {
            id: 'ev-founder-policy',
            label: 'Founder safety policy',
            url: null,
            sourceType: 'founder-input',
            observedAt: '2026-07-29T08:05:00.000Z',
            freshness: 'fresh',
            note: 'Every external action requires approval; cold social DMs are disabled.',
        },
    ],
    dataGaps: [
        'Meta professional account is not connected.',
        'TikTok owned-account analytics are not connected.',
        'Prospect discovery providers are using demo records only.',
        'No external send or publish capability is enabled.',
    ],
};
