import type { Track, Playlist } from "@/lib/stores/player-store";
import type { AmbientChannel } from "@/lib/stores/mixer-store";
import { AMBIENT_SOUND_CATALOG } from "@/lib/audio/ambient-catalog";
import catalogJson from "@/public/tracks/catalog.json";

type CatalogEntry = {
  id: string;
  title: string;
  artist: string;
  genre: string;
  category: string;
  durationS: number;
  // Historical name: despite "hls", this holds a plain `.mp3` path today. No
  // `.m3u8` manifests exist, so the hls.js branch in lib/audio/hls-player.ts
  // (gated on `.m3u8`) never activates — playback uses the native <audio>
  // path. Encrypted HLS remains a roadmap option (ADR-001, P0.5).
  hlsUrl: string;
  isPremium: boolean;
  source: string;
};

/**
 * Canonical ambience entitlement catalog shared with the Worker. The Worker
 * remains the security boundary while this list drives locks and labels here.
 */
export const AMBIENT_SOUNDS: AmbientChannel[] = AMBIENT_SOUND_CATALOG.map((sound) => ({ ...sound }));

// Full library — generated by scripts/compress-audio.cjs from the original masters.
// hlsUrl is a relative path; audioUrl() resolves it to the CDN at play time.
export const TRACKS: Track[] = (catalogJson as CatalogEntry[]).map((e) => ({
  id: e.id,
  title: e.title,
  artist: e.artist,
  genre: e.genre,
  mood: null,
  durationS: e.durationS,
  hlsUrl: e.hlsUrl,
  coverUrl: null,
  isPremium: e.isPremium,
}));

// Genre tabs, in display order (only those present in the catalog).
const GENRE_ORDER = ["Lofi Chill", "City Pop", "Cyberpunk Jazz", "Neo Synthwave", "Lofi Jazz"];
export const GENRES: string[] = GENRE_ORDER.filter((g) =>
  TRACKS.some((t) => t.genre === g)
);

export function tracksByGenre(genre: string): Track[] {
  return TRACKS.filter((t) => t.genre === genre);
}

export function genrePlaylist(genre: string): Playlist {
  return {
    id: genre,
    title: genre,
    slug: genre.toLowerCase().replace(/\s+/g, "-"),
    genre,
    coverUrl: null,
    isPremium: false,
    tracks: tracksByGenre(genre),
  };
}

// Default playlist = the whole library (used for "play all" / fallback navigation).
export const PLAYLIST: Playlist = {
  id: "all",
  title: "All Tracks",
  slug: "all",
  genre: "mixed",
  coverUrl: null,
  isPremium: false,
  tracks: TRACKS,
};
