import type { Track, Playlist } from "@/lib/stores/player-store";
import catalogJson from "@/public/tracks/catalog.json";

type CatalogEntry = {
  id: string;
  title: string;
  artist: string;
  genre: string;
  category: string;
  durationS: number;
  hlsUrl: string;
  isPremium: boolean;
  source: string;
};

// Full library — generated by scripts/compress-audio.cjs from the original masters.
// hlsUrl is a relative path; audioUrl() resolves it to the CDN at play time.
export const TRACKS: Track[] = (catalogJson as CatalogEntry[]).map((e) => ({
  id: e.id,
  title: e.title,
  artist: e.artist,
  genre: e.genre,
  mood: null,
  durationS: e.durationS,
  hlsUrl: e.hlsUrl,
  coverUrl: null,
  isPremium: e.isPremium,
}));

// Genre tabs, in display order (only those present in the catalog).
const GENRE_ORDER = ["Lofi Chill", "City Pop", "Cyberpunk Jazz", "Chill Synthwave", "Lofi Jazz"];
export const GENRES: string[] = GENRE_ORDER.filter((g) =>
  TRACKS.some((t) => t.genre === g)
);

export function tracksByGenre(genre: string): Track[] {
  return TRACKS.filter((t) => t.genre === genre);
}

export function genrePlaylist(genre: string): Playlist {
  return {
    id: genre,
    title: genre,
    slug: genre.toLowerCase().replace(/\s+/g, "-"),
    genre,
    coverUrl: null,
    isPremium: false,
    tracks: tracksByGenre(genre),
  };
}

// Default playlist = the whole library (used for "play all" / fallback navigation).
export const PLAYLIST: Playlist = {
  id: "all",
  title: "All Tracks",
  slug: "all",
  genre: "mixed",
  coverUrl: null,
  isPremium: false,
  tracks: TRACKS,
};
