import Link from 'next/link';
import type { Metadata } from 'next';
import { PolicyPage } from '@/components/policies/PolicyPage';

export const metadata: Metadata = {
    title: 'Privacy Policy',
    description: 'How Virzy Guns Production handles information across its public website and public VGP services.',
    alternates: { canonical: '/privacy' },
    openGraph: {
        title: 'Privacy Policy | Virzy Guns Production',
        description: 'Privacy information for the public Virzy Guns Production website and services.',
        url: 'https://www.virzyguns.com/privacy',
    },
    robots: {
        index: true,
        follow: true,
    },
};

const listClass = 'list-disc space-y-2 pl-5 marker:text-sky-200/45';

export default function PrivacyPage() {
    return (
        <PolicyPage
            eyebrow="Virzy Guns Production"
            title="Privacy Policy"
            summary="This policy explains how Virzy Guns Production handles information on its public website and public VGP-operated services. Product-specific notices apply where a product has its own data flows."
            effectiveDate="August 8, 2026"
            sections={[
                {
                    title: 'Scope and operator',
                    content: (
                        <>
                            <p>
                                This policy applies to the public Virzy Guns Production website at www.virzyguns.com and relevant public services operated by VGP. Virzy Guns Production is operated by Virzy Guns.
                            </p>
                            <p>
                                Products with distinct accounts, subscriptions, or provider connections may present additional notices for those specific data flows. Founder OS provider data is covered by the separate{' '}
                                <Link className="text-sky-100 underline decoration-sky-200/30 underline-offset-4 hover:text-white" href="/founder-os/privacy">
                                    Founder OS Privacy Policy
                                </Link>
                                .
                            </p>
                        </>
                    ),
                },
                {
                    title: 'Information we process',
                    content: (
                        <ul className={listClass}>
                            <li>Newsletter information such as your email address, a name or context label provided or generated by the subscription form, interest tags, and subscription status.</li>
                            <li>Newsletter engagement timestamps, such as whether a campaign email was opened or a tracked link was clicked.</li>
                            <li>Short-lived technical request information, including an IP address or related request metadata used for rate limiting, security, and troubleshooting.</li>
                            <li>Browser-local preferences such as bookmarked articles, the beat-store guide status, and the newsletter-subscribed marker. These values are stored in your browser and are not a cross-device account.</li>
                            <li>Information you choose to send to founder@virzyguns.com through your own email provider. The public website does not currently provide a contact form that stores message contents.</li>
                        </ul>
                    ),
                },
                {
                    title: 'How we use information',
                    content: (
                        <ul className={listClass}>
                            <li>Send requested VGP updates, launch notes, and newsletter messages.</li>
                            <li>Maintain subscription status and process unsubscribe requests.</li>
                            <li>Operate, improve, and troubleshoot public website features.</li>
                            <li>Prevent abuse, enforce request limits, protect systems, and investigate operational errors.</li>
                            <li>Respond to privacy, support, or other messages you send to the owner contact.</li>
                        </ul>
                    ),
                },
                {
                    title: 'BeatStars and external services',
                    content: (
                        <p>
                            BeatStars provides embedded previews, store content, licensing checkout, and purchase processing for the beat catalog. When you load or use those features, BeatStars may process technical information under its own policies. The VGP website does not collect your BeatStars payment credentials; the written license and purchase terms shown through the official checkout control the transaction. Other external music, social, or product links are governed by the policies of the service you choose to visit.
                        </p>
                    ),
                },
                {
                    title: 'Infrastructure and sharing',
                    content: (
                        <p>
                            Limited information may be processed by infrastructure providers that host the website, database, abuse-prevention systems, or email-delivery systems. They receive information only as needed to provide those services. Information may also be disclosed when required by law or reasonably necessary to protect users, rights, or system security.
                        </p>
                    ),
                },
                {
                    title: 'Your choices and requests',
                    content: (
                        <>
                            <ul className={listClass}>
                                <li>Use the unsubscribe link in a newsletter email to stop future messages. Unsubscribe changes the subscription status; it does not by itself erase every historical record.</li>
                                <li>Clear browser-local preferences through your browser settings.</li>
                                <li>Request access, correction, or deletion by emailing founder@virzyguns.com. We may verify the request before acting on it.</li>
                            </ul>
                            <p>
                                We may retain limited information when reasonably needed for security, fraud prevention, dispute resolution, legal obligations, or reliable operation. This policy does not promise a fixed retention period or deletion deadline.
                            </p>
                        </>
                    ),
                },
                {
                    title: 'Security and international processing',
                    content: (
                        <p>
                            Reasonable technical and organizational safeguards are used for the public services. No storage or transmission method can be guaranteed completely secure. VGP and its service providers may process information in countries other than yours, subject to applicable safeguards and law.
                        </p>
                    ),
                },
                {
                    title: 'Policy updates',
                    content: (
                        <p>
                            This policy may be updated when public services or applicable requirements change. Material updates will be posted on this page with a revised effective date.
                        </p>
                    ),
                },
            ]}
        />
    );
}
