#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

export const ALL_BPMS = [130,135,140,145,150,155,160,165,170,175,180];
export const INDEXABLE_BPMS = [180,170,165,175,160,150];
const REQUIRED = ['README_FIRST.md','DATA_DICTIONARY.md','CODEX_PROMPT.md','MASTER_ANALYSIS.md','SOURCES.md','strategy_config.json','royalty_summary_metrics.json','raw_distrokid_results.csv','keyword_opportunities_vidiq.csv','vidiq_outlier_evidence.csv','title_theme_signals_h1_2026.csv','top_tracks_h1_2026.csv','youtube_top_tracks_h1_2026.csv','youtube_artists_h1_2026.csv','youtube_countries_h1_2026.csv','youtube_monthly_2025_2026H1.csv','artists_h1_2026.csv','countries_h1_2026.csv','luna_2025_monthly.csv','store_economics_2025.csv','stores_h1_2026.csv','store_reporting_lag_diagnostics.csv','backlog_watchlist.csv','isrc_title_conflicts.csv','YOUTUBE_CHANNEL_CONTEXT.md','DISTROKID_COMPLETE_CATALOG.xlsx','DistroKid_Royalty_Analysis_Aug2026_PERFECT.xlsx','DistroKid_Royalty_Executive_Report_Aug2026_PERFECT.pdf','MASTER_ANALYSIS.pdf'];

export function parseCsv(text) {
  const out=[]; let row=[], field='', quoted=false;
  for(let i=0;i<text.length;i++){ const c=text[i], n=text[i+1];
    if(quoted){ if(c==='"'&&n==='"'){field+='"';i++;} else if(c==='"') quoted=false; else field+=c; continue; }
    if(c==='"') quoted=true; else if(c===','){row.push(field);field='';}
    else if(c==='\n'){row.push(field.replace(/\r$/,''));out.push(row);row=[];field='';} else field+=c;
  }
  if(field!==''||row.length){row.push(field);out.push(row);}
  if(!out.length) return [];
  const header=out[0]; return out.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]??''])));
}
const esc=v=>{const s=v==null?'':String(v);return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};
export function renderCsv(rows, cols){return cols.join(',')+'\n'+rows.map(r=>cols.map(c=>esc(r[c])).join(',')).join('\n')+'\n';}
export function extractBpm(title){const m=[...String(title??'').matchAll(/\b((?:13[05]|14[05]|15[05]|16[05]|17[05]|180))\s*(?:BPM|SPM)\b/gi)].map(x=>Number(x[1]));return new Set(m).size===1?m[0]:null;}
const norm=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const money=v=>Number(v||0).toFixed(6), integer=v=>String(Math.round(Number(v||0)));
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function unique(values,name){const s=new Set();for(const v of values){if(!v||s.has(v))throw Error(name+' duplicated/empty source ID: '+v);s.add(v);}}
function requireCols(rows,cols,name){if(!rows.length)throw Error(name+' empty');for(const c of cols)if(!(c in rows[0]))throw Error(name+' missing column '+c);}
function validDate(v,month=false){return month?/^\d{4}-(0[1-9]|1[0-2])$/.test(v):/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'));}
function sourceFiles(input){
 const lines=fs.readFileSync(path.join(input,'SHA256SUMS.txt'),'utf8').split(/\r?\n/).filter(Boolean);
 if(lines.length!==30)throw Error('Expected 30 SHA256 source entries, got '+lines.length);
 const entries=lines.map(x=>{const m=x.match(/^([0-9a-f]{64})\s+(.+)$/i);if(!m)throw Error('Invalid checksum line');return{sha:m[1].toLowerCase(),name:m[2]};});
 unique(entries.map(x=>x.name),'SHA256SUMS');
 const files=entries.map(x=>{if(path.isAbsolute(x.name)||x.name.includes('..'))throw Error('Unsafe source path '+x.name);const p=path.join(input,x.name);if(!fs.existsSync(p))throw Error('Missing source '+x.name);const actual=hash(p);if(actual!==x.sha)throw Error('Checksum mismatch '+x.name);return{name:x.name,sha256:actual,bytes:fs.statSync(p).size};});
 for(const f of REQUIRED)if(!files.some(x=>x.name===f))throw Error('Required source absent '+f);
 return files.sort((a,b)=>a.name.localeCompare(b.name));
}
function load(input){
 const files=sourceFiles(input), read=(name,cols)=>{const r=parseCsv(fs.readFileSync(path.join(input,name),'utf8'));requireCols(r,cols,name);return r;};
 const raw=read('raw_distrokid_results.csv',['Date Inserted','Reporting Date','Sale Month','Store','Artist','Title','ISRC','UPC','Quantity','Source Type','Earnings (USD)']);
 raw.forEach((r,i)=>{if(!validDate(r['Date Inserted'])||!validDate(r['Reporting Date'])||!validDate(r['Sale Month'],true))throw Error('Invalid date in raw row '+(i+2));if(!Number.isFinite(Number(r.Quantity))||!Number.isFinite(Number(r['Earnings (USD)'])))throw Error('Invalid numeric value in raw row '+(i+2));});
 const keywords=read('keyword_opportunities_vidiq.csv',['funnel','keyword','estimated_monthly_search_global','competition_score','overall_score']);unique(keywords.map(r=>r.funnel+'|'+r.keyword),'keyword source');
 const outliers=read('vidiq_outlier_evidence.csv',['funnel','query','channel','video_id','title']);unique(outliers.map(r=>r.video_id),'vidIQ video source');
 const conflicts=read('isrc_title_conflicts.csv',['isrc','titles']);unique(conflicts.map(r=>r.isrc),'ISRC conflict source');
 const catalogPath=path.resolve(process.cwd(),'flowstate','public','tracks','catalog.json');if(!fs.existsSync(catalogPath))throw Error('Missing Flow catalog '+catalogPath);
 const catalog=JSON.parse(fs.readFileSync(catalogPath,'utf8'));if(!Array.isArray(catalog))throw Error('Flow catalog not array');unique(catalog.map(x=>String(x.id)),'Flow catalog');
 return {files,raw,keywords,outliers,conflicts,catalog};
}
function bpmAggregate(raw){
 const map=new Map(ALL_BPMS.map(b=>[b,{bpm:b,rows:0,isrcs:new Set(),quantity:0,earnings:0,youtubeEarnings:0,titles:new Map()}]));
 for(const r of raw)if(r.Artist==='Virzy Guns'&&/^2026-0[1-6]$/.test(r['Sale Month'])){const b=extractBpm(r.Title);if(!b)continue;const x=map.get(b),q=Number(r.Quantity),e=Number(r['Earnings (USD)']);x.rows++;if(r.ISRC)x.isrcs.add(r.ISRC);x.quantity+=q;x.earnings+=e;if(String(r.Store).toLowerCase().startsWith('youtube'))x.youtubeEarnings+=e;const t=x.titles.get(r.Title)||{title:r.Title,quantity:0,earnings:0};t.quantity+=q;t.earnings+=e;x.titles.set(r.Title,t);}
 return map;
}
function repositoryInfo(){try{return{branch:execFileSync('git',['branch','--show-current'],{encoding:'utf8'}).trim()||'detached',commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()};}catch{return{branch:'not_available',commit:'not_available'};}}
function manifestJson(files){return JSON.stringify({schema_version:1,repository:repositoryInfo(),source_count:files.length,verified_count:files.length,files},null,2)+'\n';}
function build(input,src){
 const {files,raw,keywords,outliers,conflicts,catalog}=src, agg=bpmAggregate(raw), conflictSet=new Set(conflicts.map(r=>r.isrc));
 const rawGroups=new Map();
 for(const r of raw)if(r.ISRC&&r['Source Type']==='Song'){const g=rawGroups.get(r.ISRC)||{isrc:r.ISRC,artists:new Set(),titles:new Set(),upcs:new Set(),quantity:0,earnings:0,bpms:new Set()};g.artists.add(r.Artist);g.titles.add(r.Title);if(r.UPC)g.upcs.add(r.UPC);g.quantity+=Number(r.Quantity);g.earnings+=Number(r['Earnings (USD)']);const b=extractBpm(r.Title);if(b)g.bpms.add(b);rawGroups.set(r.ISRC,g);}
 const canonical=[...rawGroups.values()].sort((a,b)=>a.isrc.localeCompare(b.isrc)).map(g=>{const conflict=conflictSet.has(g.isrc);return{canonical_id:'isrc:'+g.isrc,entity_type:'track',artist:[...g.artists].sort().join(' | '),title:[...g.titles].sort().join(' | '),isrc:g.isrc,upc:[...g.upcs].sort().join(' | '),bpm:g.bpms.size===1&&!conflict?[...g.bpms][0]:'',bpm_source:g.bpms.size===1&&!conflict?'explicit_title_pattern_pending_review':conflict?'conflict':'not_available',flow_track_id:'',dsp_url:'',youtube_id:'',confidence:conflict?'hold':'candidate',review_reason:conflict?'known_isrc_title_conflict':'normalized_identity_requires_review',h1_quantity:integer(g.quantity),h1_earnings_usd:money(g.earnings)}});
 for(const t of [...catalog].sort((a,b)=>String(a.id).localeCompare(String(b.id))))canonical.push({canonical_id:'flow:'+t.id,entity_type:'track',artist:t.artist||'',title:t.title||'',isrc:'',upc:'',bpm:'',bpm_source:'not_available',flow_track_id:t.id,dsp_url:'',youtube_id:'',confidence:'candidate',review_reason:'flow_catalog_has_no_verified_distrokid_crosswalk',h1_quantity:'',h1_earnings_usd:''});
 const manual=conflicts.map(r=>({review_type:'isrc_title_conflict',source_id:r.isrc,details:r.titles,action:'manual_review_required',severity:'high'}));
 const identity=new Map();for(const g of rawGroups.values())for(const a of g.artists)for(const t of g.titles)identity.set(norm(a)+'|'+norm(t),g.isrc);
 const crosswalk=[...catalog].map(t=>{const c=identity.get(norm(t.artist)+'|'+norm(t.title));return{flow_track_id:t.id,flow_artist:t.artist,flow_title:t.title,candidate_isrc:c||'',match_status:c?'candidate_manual_review':'unmatched',auto_merge:'no',reason:c?'normalized_artist_title_candidate_only':'no_exact_normalized_candidate'}}).sort((a,b)=>a.flow_track_id.localeCompare(b.flow_track_id));
 const bpm=ALL_BPMS.map(b=>{const x=agg.get(b),kw=keywords.filter(r=>r.funnel==='CADENZ'&&(extractBpm(r.keyword)===b||r.keyword.toLowerCase().includes('running music'))),out=outliers.filter(r=>r.funnel==='CADENZ'&&(extractBpm(r.query)===b||r.query.toLowerCase().includes('running music'))),idx=INDEXABLE_BPMS.includes(b);return{bpm:b,selector_state:'available',page_route:idx?'/cadenz/running-music/'+b+'-bpm':'/cadenz/running-music',indexable:idx?'yes':'no',canonical_route:idx?'/cadenz/running-music/'+b+'-bpm':'/cadenz/running-music',evidence_tier:idx?'B':'C',title_reference_count:x.titles.size,first_party_status:'not_available',royalty_quantity:integer(x.quantity),royalty_earnings_usd:money(x.earnings),youtube_earnings_usd:money(x.youtubeEarnings),keyword_evidence:kw.length?'vidiq_estimate':'not_available',outlier_evidence:out.length?'vidiq_outlier_snapshot':'not_available'}});
 const scores=bpm.map(r=>({opportunity_id:'cadenz-bpm-'+r.bpm,funnel:'CADENZ',asset_type:'collection',primary_intent:r.bpm+' BPM running music',evidence_first_party:'not_available',royalty_evidence:r.royalty_earnings_usd!=='0.000000'?'h1_2026_sale_month_aggregate':'not_available',independent_evidence:r.outlier_evidence!=='not_available'?r.outlier_evidence:r.keyword_evidence,product_fit:'direct',asset_publishable:r.title_reference_count?'reference_only_pending_crosswalk':'no',cannibalization_risk:r.indexable==='yes'?'reviewed_low_for_bpm_route':'canonical_to_hub',final_tier:r.evidence_tier,decision:r.indexable==='yes'?'indexable_candidate':'hub_filter_only',reason:r.indexable==='yes'?'Prioritized by supplied evidence before GSC.':'Coverage retained in hub/filter architecture without standalone URL.'})).concat([
 {opportunity_id:'flow-work-music',funnel:'FLOW',asset_type:'collection',primary_intent:'work music',evidence_first_party:'not_available',royalty_evidence:'title_theme_signal_available',independent_evidence:'vidiq_outlier_snapshot',product_fit:'direct',asset_publishable:'yes_existing_flow_catalog',cannibalization_risk:'low_pilot',final_tier:'B',decision:'en_pilot',reason:'Distinct collection intent with existing Flow product fit.'},
 {opportunity_id:'flow-coding-music',funnel:'FLOW',asset_type:'collection',primary_intent:'coding music',evidence_first_party:'not_available',royalty_evidence:'title_theme_signal_available',independent_evidence:'vidiq_estimate',product_fit:'direct',asset_publishable:'yes_existing_flow_catalog',cannibalization_risk:'low_pilot',final_tier:'B',decision:'en_pilot',reason:'Distinct collection intent with existing Flow product fit.'}]);
 const keywordMap=keywords.map(r=>{const b=r.funnel==='CADENZ'?extractBpm(r.keyword):null;const k=r.keyword.toLowerCase();const route=r.funnel==='CADENZ'?(b&&INDEXABLE_BPMS.includes(b)?'/cadenz/running-music/'+b+'-bpm':'/cadenz/running-music'):(k.includes('coding')?'/en/coding-music':k.includes('work')?'/en/work-music':'/en/pomodoro-timer-with-music');return{funnel:r.funnel,keyword:r.keyword,asset_route:route,evidence_source:'vidiq_estimate',search_volume_estimate:r.estimated_monthly_search_global,competition_estimate:r.competition_score,no_first_party_claim:'yes'}});
 const queue=INDEXABLE_BPMS.map((b,i)=>({queue_order:i+1,scope:'root',route:'/cadenz/running-music/'+b+'-bpm',asset_type:'collection',primary_intent:b+' BPM running music',evidence_tier:'B',action:'review_crosswalk_then_publish',blocker:'verified_asset_urls_and_ownership'})).concat([
 {queue_order:7,scope:'root',route:'/cadenz/running-music',asset_type:'hub',primary_intent:'running music by BPM',evidence_tier:'B',action:'publish_hub',blocker:'verified_asset_urls_and_ownership'},
 {queue_order:8,scope:'flow',route:'/en/work-music',asset_type:'collection',primary_intent:'work music',evidence_tier:'B',action:'publish_en_pilot',blocker:'runtime_QA'},
 {queue_order:9,scope:'flow',route:'/en/coding-music',asset_type:'collection',primary_intent:'coding music',evidence_tier:'B',action:'publish_en_pilot',blocker:'runtime_QA'},
 {queue_order:10,scope:'flow',route:'/en/pomodoro-timer-with-music',asset_type:'existing_page',primary_intent:'pomodoro music',evidence_tier:'B',action:'strengthen_existing_url',blocker:'runtime_QA'}]);
 const collections=[{scope:'root',route:'/cadenz/running-music',indexable:'yes',canonical:'/cadenz/running-music',evidence_tier:'B',status:'candidate'},...INDEXABLE_BPMS.map(b=>({scope:'root',route:'/cadenz/running-music/'+b+'-bpm',indexable:'yes',canonical:'/cadenz/running-music/'+b+'-bpm',evidence_tier:'B',status:'candidate'})),{scope:'flow',route:'/en/work-music',indexable:'yes',canonical:'/en/work-music',evidence_tier:'B',status:'en_pilot'},{scope:'flow',route:'/en/coding-music',indexable:'yes',canonical:'/en/coding-music',evidence_tier:'B',status:'en_pilot'},{scope:'flow',route:'/en/pomodoro-timer-with-music',indexable:'yes_existing',canonical:'/en/pomodoro-timer-with-music',evidence_tier:'B',status:'strengthen_existing'}];
 const registry=collections.map(r=>({route:r.route,site_scope:r.scope,funnel:r.scope==='root'?'CADENZ':'FLOW',primary_intent:r.scope==='root'?'running music by BPM':r.route.includes('coding')?'coding music':r.route.includes('work-music')?'work music':'pomodoro music',locale_release:r.scope==='root'?'default':'en',index_state:r.indexable.startsWith('yes')?'indexable_candidate':'draft',canonical:r.canonical,schema_types:'CollectionPage|BreadcrumbList|ItemList',cta_destination:r.scope==='root'?'/cadenz':'/en',evidence_tier:r.evidence_tier,review_status:'manual_review_required_for_assets'}));
 const links=[{from_route:'/cadenz/running-music',to_route:'/cadenz',relation:'parent_product'},...INDEXABLE_BPMS.flatMap((b,i)=>[{from_route:'/cadenz/running-music',to_route:'/cadenz/running-music/'+b+'-bpm',relation:'hub_to_bpm'},{from_route:'/cadenz/running-music/'+b+'-bpm',to_route:'/cadenz/running-music',relation:'bpm_to_hub'},i<INDEXABLE_BPMS.length-1?{from_route:'/cadenz/running-music/'+b+'-bpm',to_route:'/cadenz/running-music/'+INDEXABLE_BPMS[i+1]+'-bpm',relation:'adjacent_bpm'}:null].filter(Boolean)),{from_route:'/en/work-music',to_route:'/en/pomodoro-timer-with-music',relation:'focus_experience'},{from_route:'/en/coding-music',to_route:'/en/pomodoro-timer-with-music',relation:'focus_experience'}];
 const drafts=[
 ['Virzy Guns','owner_confirmation_required','180 BPM Running Music | Cyberpunk Synthwave Cadence','https://www.virzyguns.com/cadenz/running-music/180-bpm','B'],
 ['Virzy Guns','owner_confirmation_required','170 BPM Running Music | Cyberpunk Synthwave Cadence','https://www.virzyguns.com/cadenz/running-music/170-bpm','B'],
 ['Virzy Guns','owner_confirmation_required','165 BPM Running Music | Cyberpunk Synthwave Cadence','https://www.virzyguns.com/cadenz/running-music/165-bpm','B'],
 ['Virzy Guns','owner_confirmation_required','Running Music by BPM | CADENZ','https://www.virzyguns.com/cadenz/running-music','B'],
 ['Chill Music Division','manual_owner_verification','Work Music for Focus Blocks | Flow','https://flow.virzyguns.com/en/work-music','B'],
 ['Chill Music Division','manual_owner_verification','Coding Music for Deep Focus | Flow','https://flow.virzyguns.com/en/coding-music','B'],
 ['Chill Music Division','manual_owner_verification','Pomodoro Focus Music | Flow Timer','https://flow.virzyguns.com/en/pomodoro-timer-with-music','B']
 ].map(x=>({channel:x[0],channel_status:x[1],format:'long_form',title:x[2],opening_1:'Original music for a focused session; keep the claim factual and concise.',opening_2:'Open the destination page for the collection and product experience.',destination_url:x[3],playlist:'Manual recommendation; create only with useful inventory.',thumbnail_brief:'Readable title, restrained artwork, no hype or health claim.',factual_bpm_spm_flag:x[0]==='Virzy Guns'?'BPM source-backed; SPM requires owner confirmation':'not_applicable',evidence_tier:x[4],mutation_policy:'manual_only'}));
 const playlists=drafts.map(r=>({playlist:r.channel+' — '+r.title,channel_status:r.channel_status,inventory_status:'useful_inventory_required',recommended_route:new URL(r.destination_url).pathname}));
 const luna=raw.filter(r=>r.Store==='Luna').length,lunaQ=raw.filter(r=>r.Artist==='LUNA Q').length;
 const report=['# VGP Organic Discovery Engine - Master Execution Report','','- SHA256SUMS.txt verified before output write.','- Source entries verified: '+files.length+'/30.','- Raw royalty data remains in Google Drive; outputs are derived decision tables.','- Sale Month is the operating trend date; Date Inserted is reporting timing.','- Quantity remains store-reported quantity and is not labeled stream.','- Luna is a store ('+luna+' raw rows); LUNA Q is an artist ('+lunaQ+' raw rows).','- All 11 BPM selectors retained; six standalone indexable candidates and five Tier C hub-only candidates.','- Flow catalog contains '+catalog.length+' tracks labeled Virzy Guns; no CMD bulk relabel.','- No mass track pages: workbook metadata is incomplete and cross-brand identity is unverified.','- GSC and YouTube Analytics exports are not present: first-party fields are not_available.','- Bright Data rendered crawl is blocked_external_data until CLI/auth/output exist.','','## Acceptance status','','- Validation passed in memory; writes occur only after checksums and schemas pass.','- YouTube output is manual-only; no API mutation or upload.','- Deployment was not performed by this generator.','','See Where_I_disagreed_with_the_supplied_strategy.md for decisions.'].join('\n')+'\n';
 const disagreement=['# Where I disagreed with the supplied strategy','','- 165 BPM is promoted to the third priority because supplied H1 2026 evidence shows approximately 912 quantity and 4.43 YouTube earnings in the analysis context.','- All 11 BPM values remain in navigation/filter architecture, but only 180, 170, 165, 175, 160, and 150 BPM get standalone indexable candidates before GSC confirmation.','- I did not create mass track pages: the workbook has 135 metadata rows with incomplete genre/language fields and Flow has 295 tracks labeled Virzy Guns.','- I did not bulk-relabel Flow tracks to Chill Music Division or create a competing /pomodoro-music URL.','- YouTube is a manual package only; owner verification is required for channels and mutations.','','Every unsupported external claim remains not_available or blocked_external_data.'].join('\n')+'\n';
 const cols={canonical_catalog:['canonical_id','entity_type','artist','title','isrc','upc','bpm','bpm_source','flow_track_id','dsp_url','youtube_id','confidence','review_reason','h1_quantity','h1_earnings_usd'],catalog_identity_crosswalk:['flow_track_id','flow_artist','flow_title','candidate_isrc','match_status','auto_merge','reason'],manual_review_required:['review_type','source_id','details','action','severity'],seo_opportunity_scores:['opportunity_id','funnel','asset_type','primary_intent','evidence_first_party','royalty_evidence','independent_evidence','product_fit','asset_publishable','cannibalization_risk','final_tier','decision','reason'],bpm_opportunity_map:['bpm','selector_state','page_route','indexable','canonical_route','evidence_tier','title_reference_count','first_party_status','royalty_quantity','royalty_earnings_usd','youtube_earnings_usd','keyword_evidence','outlier_evidence'],keyword_asset_map:['funnel','keyword','asset_route','evidence_source','search_volume_estimate','competition_estimate','no_first_party_claim'],priority_content_queue:['queue_order','scope','route','asset_type','primary_intent','evidence_tier','action','blocker'],track_page_candidates:['candidate_type','candidate_count','indexable','decision','reason'],collection_page_candidates:['scope','route','indexable','canonical','evidence_tier','status'],seo_page_registry:['route','site_scope','funnel','primary_intent','locale_release','index_state','canonical','schema_types','cta_destination','evidence_tier','review_status'],internal_link_map:['from_route','to_route','relation'],youtube_title_description_drafts:['channel','channel_status','format','title','opening_1','opening_2','destination_url','playlist','thumbnail_brief','factual_bpm_spm_flag','evidence_tier','mutation_policy'],youtube_playlist_plan:['playlist','channel_status','inventory_status','recommended_route']};
 const rows={canonical_catalog:canonical,catalog_identity_crosswalk:crosswalk,manual_review_required:manual,seo_opportunity_scores:scores,bpm_opportunity_map:bpm,keyword_asset_map:keywordMap,priority_content_queue:queue,track_page_candidates:[{candidate_type:'mass_track_pages',candidate_count:0,indexable:'no',decision:'hold',reason:'135 metadata rows are incomplete and Flow cross-brand identity is unverified.'}],collection_page_candidates:collections,seo_page_registry:registry,internal_link_map:links,youtube_title_description_drafts:drafts,youtube_playlist_plan:playlists};
 const externalGate=JSON.stringify({schema_version:1,bright_data:{status:'blocked_external_data',cli_installed:true,authenticated:false,evidence:'bdata zones returned No API key found after bdata login timed out'},gsc:{status:'not_available',credentials:'not_configured'},youtube_analytics:{status:'not_available',export_present:false},claims_policy:'Do not claim crawl, render, ranking, or first-party analytics results until runnable output is stored.'},null,2)+'\n';
  const outputs=new Map([['input_manifest.json',manifestJson(files)],['external_gate_status.json',externalGate],['MASTER_EXECUTION_REPORT.md',report],['Where_I_disagreed_with_the_supplied_strategy.md',disagreement]]);
 for(const [name,c] of Object.entries(cols))outputs.set(name+'.csv',renderCsv(rows[name],c));
 return {outputs,stats:{rawRows:raw.length,canonicalRows:canonical.length,flowTracks:catalog.length,h1CadenceRows:[...agg.values()].reduce((n,x)=>n+x.rows,0),lunaRows:luna,lunaQRows:lunaQ,conflicts:conflicts.length}};
}
function writeOutputs(dir,outputs){const names=[...outputs.keys()].sort((a,b)=>a.localeCompare(b));const sums=names.map(n=>hashBuffer(outputs.get(n))+'  '+n).join('\n')+'\n';fs.mkdirSync(dir,{recursive:true});for(const n of names)fs.writeFileSync(path.join(dir,n),outputs.get(n),'utf8');fs.writeFileSync(path.join(dir,'OUTPUT_SHA256SUMS.txt'),sums,'utf8');}
function hashBuffer(value){return crypto.createHash('sha256').update(value).digest('hex');}
export function generate({inputDir,outputDir,dryRun=false}){const src=load(inputDir),result=build(inputDir,src);if(!dryRun)writeOutputs(outputDir,result.outputs);return{...result.stats,outputFiles:[...result.outputs.keys()].sort(),dryRun};}
function args(argv){const a={};for(let i=0;i<argv.length;i++){if(argv[i]==='--dry-run')a.dryRun=true;else if(argv[i]==='--input')a.inputDir=argv[++i];else if(argv[i]==='--output')a.outputDir=argv[++i];else throw Error('Unknown argument '+argv[i]);}return a;}
if(process.argv[1]&&import.meta.url.endsWith(process.argv[1].replace(/\\/g,'/'))){try{const a=args(process.argv.slice(2)),input=path.resolve(a.inputDir||'G:/My Drive/codex_traffic_pack');if(!a.dryRun&&!a.outputDir)throw Error('--output is required unless --dry-run');const output=path.resolve(a.outputDir||path.join(input,'runs','manual'));console.log(JSON.stringify(generate({inputDir:input,outputDir:output,dryRun:Boolean(a.dryRun)}),null,2));}catch(e){console.error('organic-discovery generator blocked before write:',e?.message||e);process.exitCode=1;}}
